### ISSUE TITLE
[Bug] All tech now have a Metallurgic Science Pack requirement

### ISSUE THREAD

**Issue by Hi-ImKyle** [Brabra94/Fundryu#5]
What ever you are doing with technology, you are somehow making ALL tech require Metallurgic Science Packs causing the game to be impossible to play with the mod installed.

![image](https://github.com/user-attachments/assets/5be9f134-b8c1-4d79-a9b9-caa37a5c361c)

**Comment by Hi-ImKyle** [comment]
[Offending code line](https://github.com/Brabra94/Fundryu/commit/df6e9e552aac639af5d402c4377471999fd35741#diff-e2ebf1022e98686383b50cc2fb26913bfea25f051a17fdd9a2e8174ae110141cR65)

Why is this even a thing, why are you adding this science pack to all technology that doesn't have it?

**Comment by Brabra94** [comment]
oops

**Comment by Brabra94** [comment]
Try the new version on the mod page, it should be fixed.

**Comment by Hi-ImKyle** [comment]
Yep, looks fine now 👍
