### ISSUE TITLE
[Bug] Electronic Circuits now take tungston carbide [0.2.2]

### ISSUE THREAD

**Issue by Quasky** [Brabra94/Fundryu#6]
Electronic Circuits now take Tungsten Carbide to make, this breaks progression.

![image](https://github.com/user-attachments/assets/b2c80dc8-cd7a-4cb2-9f73-ae84afb24abd)

**Comment by Brabra94** [comment]
Electronic Circuits in the foundry ????

**Comment by Brabra94** [comment]
I didn't add a recipe to produce electronic in the foundry or I'm too tired ?

**Comment by Quasky** [comment]
The image is the normal crafting recipe. (by hand, assembler, electro plant)
I just updated to 0.2.3 and it's fixed.
